dist: xenial
sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install pytest-cov
  - pip install coveralls
script:
  - pytest -v --cov="." test.py
after_success:
  - coveralls