site_name: Lazyparser
use_directory_urls: false
theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
    - navigation.footer
    - content.code.copy

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - index.md
  - documentation.md
  - reference.md

plugins:
  - admonition
  - search
  - mkdocstrings
